In [301]:
import sqlite3
import csv
import glob
import pandas as pd

In [302]:
file_extension = ".csv"

In [303]:
all_filenames = [i for i in glob.glob(f"*{file_extension}")]

In [304]:
print(all_filenames)

['shipping_data_1.csv', 'shipping_data_0.csv', 'shipping_data_2.csv']

In [305]:
df1 = pd.read_csv('shipping_data_0.csv')
df2 = pd.read_csv('shipping_data_1.csv')
df3 = pd.read_csv('shipping_data_2.csv')

In [306]:
df1.head()

,origin_warehouse,destination_store,product,on_time,product_quantity,driver_identifier
0,d5566b15-b071-4acf-8e8e-c98433083b2d,50d33715-4c77-4dd9-8b9d-ff1ca372a2a2,lotion,True,59,d8da0460-cf39-4f38-9fff-6c9b4e344d8a
1,c42f0de8-b4f0-4167-abd1-ae79e5e18eea,172eb8f3-1033-4fb6-b66b-d0df09df3161,windows,True,28,293ccaec-6592-4f04-aae5-3e238fe62614
2,b145f396-de9b-42f1-9cc9-f5b52c3a941c,65e4544d-42ae-4751-9580-bdcb90e5fcda,skis,True,63,80988f09-91a3-4e1b-8e69-13551c53f318
3,f4372224-759f-43b3-bc83-ca6106bba1af,745bee4e-710c-4538-8df1-5c146e1092a6,bikes,True,47,5f79b402-655f-4d8e-8ff3-5ef05870e0ad
4,49d0edae-9091-41bb-a08d-ab1c66bd08d5,425b7a1a-b744-4c6b-898e-d424dd8cf18e,candy,False,73,58beb5d3-98f8-4077-a964-1f04f7cb11e5

In [307]:
df2.head()

                    shipment_identifier    product  on_time
0  449263b4-6c93-4f19-8b6a-0d99a29fc637      pants    False
1  449263b4-6c93-4f19-8b6a-0d99a29fc637      pants    False
2  449263b4-6c93-4f19-8b6a-0d99a29fc637      pants    False
3  449263b4-6c93-4f19-8b6a-0d99a29fc637  keyboards    False
4  449263b4-6c93-4f19-8b6a-0d99a29fc637  keyboards    False

In [308]:
df3.head()

,shipment_identifier,origin_warehouse,destination_store,driver_identifier
0,449263b4-6c93-4f19-8b6a-0d99a29fc637,bb75bf7d-c008-4267-bf92-6089cff5fe56,5e9405de-a078-4b00-99c6-96564568b63c,c12025e6-6f9c-4728-8c3c-9f840bde6f1a
1,76e5b84a-9d09-4efb-8b43-a0c932b958bb,372fd2b1-b2a7-4553-b6d7-426a1bc88e56,e34973c8-9ca9-4a06-b497-7a8b49625fc2,85b8d394-a67c-48b6-b1de-55be323ba622
2,b541a47d-89b1-4805-97d0-1988832321f1,469d957f-28ef-4eac-956a-d2a42b06d3ab,fcadc756-61e9-41bb-871b-d3546c5aa981,47bdfc40-f3db-4678-b6a7-43f1e1c2fd32
3,3fc6b63d-27b4-408c-b3b3-e8e94a45b079,cd140190-a53b-4660-a5b4-cc844a6506f0,89ba200c-ca90-443a-b64f-397bce091eae,5ae3e541-2098-45b6-8d94-35d176185606
4,491ee4e8-be80-4f52-802b-d8fe1a6bd487,c6addf8b-eea6-43b8-9040-b5620b1a0d99,7aebe820-8478-4a29-a606-7c59af677e24,1f228b52-7165-4d7f-a731-3f7707aefb2a

In [309]:
df_comb23 = pd.merge(df2, df3, how='inner', on = 'shipment_identifier')
print(df_comb23)
df_final = pd.merge(df1, df_comb23, how = 'outer')
df_final

                      shipment_identifier       product  on_time  \
0    449263b4-6c93-4f19-8b6a-0d99a29fc637         pants    False
1    449263b4-6c93-4f19-8b6a-0d99a29fc637         pants    False
2    449263b4-6c93-4f19-8b6a-0d99a29fc637         pants    False
3    449263b4-6c93-4f19-8b6a-0d99a29fc637     keyboards    False
4    449263b4-6c93-4f19-8b6a-0d99a29fc637     keyboards    False
..                                    ...           ...      ...
105  c2237ca1-b7e3-40ab-b798-e1ea469301dc     keyboards     True
106  cfa8a834-54bd-4f47-99ca-8912df32913b  animal masks    False
107  cfa8a834-54bd-4f47-99ca-8912df32913b     furniture    False
108  cfa8a834-54bd-4f47-99ca-8912df32913b     furniture    False
109  cfa8a834-54bd-4f47-99ca-8912df32913b     furniture    False

                         origin_warehouse  \
0    bb75bf7d-c008-4267-bf92-6089cff5fe56
1    bb75bf7d-c008-4267-bf92-6089cff5fe56
2    bb75bf7d-c008-4267-bf92-6089cff5fe56
3    bb75bf7d-c008-4267-bf92-6089cff5fe56
4    bb75bf7d-c008-4267-bf92-6089cff5fe56
..                                    ...
105  b377e5d5-563f-475d-8c6d-b9f85ad861fd
106  5158fc84-71e0-47a1-84e9-b3e446a391ae
107  5158fc84-71e0-47a1-84e9-b3e446a391ae
108  5158fc84-71e0-47a1-84e9-b3e446a391ae
109  5158fc84-71e0-47a1-84e9-b3e446a391ae

                        destination_store  \
0    5e9405de-a078-4b00-99c6-96564568b63c
1    5e9405de-a078-4b00-99c6-96564568b63c
2    5e9405de-a078-4b00-99c6-96564568b63c
3    5e9405de-a078-4b00-99c6-96564568b63c
4    5e9405de-a078-4b00-99c6-96564568b63c
..                                    ...
105  fa60bc82-665e-4fe0-8f1f-b8a7675c2e2a
106  76f02f30-28cd-4f15-88be-9c64860d1fce
107  76f02f30-28cd-4f15-88be-9c64860d1fce
108  76f02f30-28cd-4f15-88be-9c64860d1fce
109  76f02f30-28cd-4f15-88be-9c64860d1fce

                        driver_identifier
0    c12025e6-6f9c-4728-8c3c-9f840bde6f1a
1    c12025e6-6f9c-4728-8c3c-9f840bde6f1a
2    c12025e6-6f9c-4728-8c3c-9f840bde6f1a
3    c12025e6-6f9c-4728-8c3c-9f840bde6f1a
4    c12025e6-6f9c-4728-8c3c-9f840bde6f1a
..                                    ...
105  eabecfd5-5ec5-4639-b32d-e204b34af195
106  aa4c2cd3-0f2c-4982-abd3-be7b06facc87
107  aa4c2cd3-0f2c-4982-abd3-be7b06facc87
108  aa4c2cd3-0f2c-4982-abd3-be7b06facc87
109  aa4c2cd3-0f2c-4982-abd3-be7b06facc87

[110 rows x 6 columns]

,origin_warehouse,destination_store,product,on_time,product_quantity,driver_identifier,shipment_identifier
0,d5566b15-b071-4acf-8e8e-c98433083b2d,50d33715-4c77-4dd9-8b9d-ff1ca372a2a2,lotion,True,59.0,d8da0460-cf39-4f38-9fff-6c9b4e344d8a,NaN
1,c42f0de8-b4f0-4167-abd1-ae79e5e18eea,172eb8f3-1033-4fb6-b66b-d0df09df3161,windows,True,28.0,293ccaec-6592-4f04-aae5-3e238fe62614,NaN
2,b145f396-de9b-42f1-9cc9-f5b52c3a941c,65e4544d-42ae-4751-9580-bdcb90e5fcda,skis,True,63.0,80988f09-91a3-4e1b-8e69-13551c53f318,NaN
3,f4372224-759f-43b3-bc83-ca6106bba1af,745bee4e-710c-4538-8df1-5c146e1092a6,bikes,True,47.0,5f79b402-655f-4d8e-8ff3-5ef05870e0ad,NaN
4,49d0edae-9091-41bb-a08d-ab1c66bd08d5,425b7a1a-b744-4c6b-898e-d424dd8cf18e,candy,False,73.0,58beb5d3-98f8-4077-a964-1f04f7cb11e5,NaN
...,...,...,...,...,...,...,...
215,b377e5d5-563f-475d-8c6d-b9f85ad861fd,fa60bc82-665e-4fe0-8f1f-b8a7675c2e2a,keyboards,True,NaN,eabecfd5-5ec5-4639-b32d-e204b34af195,c2237ca1-b7e3-40ab-b798-e1ea469301dc
216,5158fc84-71e0-47a1-84e9-b3e446a391ae,76f02f30-28cd-4f15-88be-9c64860d1fce,animal masks,False,NaN,aa4c2cd3-0f2c-4982-abd3-be7b06facc87,cfa8a834-54bd-4f47-99ca-8912df32913b
217,5158fc84-71e0-47a1-84e9-b3e446a391ae,76f02f30-28cd-4f15-88be-9c64860d1fce,furniture,False,NaN,aa4c2cd3-0f2c-4982-abd3-be7b06facc87,cfa8a834-54bd-4f47-99ca-8912df32913b
218,5158fc84-71e0-47a1-84e9-b3e446a391ae,76f02f30-28cd-4f15-88be-9c64860d1fce,furniture,False,NaN,aa4c2cd3-0f2c-4982-abd3-be7b06facc87,cfa8a834-54bd-4f47-99ca-8912df32913b
219,5158fc84-71e0-47a1-84e9-b3e446a391ae,76f02f30-28cd-4f15-88be-9c64860d1fce,furniture,False,NaN,aa4c2cd3-0f2c-4982-abd3-be7b06facc87,cfa8a834-54bd-4f47-99ca-8912df32913b

In [310]:
con = sqlite3.connect('shipment_database.db')
cur = con.cursor()

In [311]:
# Create tab;e
cur.execute('''CREATE TABLE shipment(origin_warehouse text, destination_store text, product text, on_time boolean, product_qty real, driver_identifier text, shipment_identifier text)''')

In [ ]:
# Insert row of data from dataframe (row by row method)
for row in df_final.itertuples():
    insert_sql = f"INSERT INTO shipment (origin_warehouse, destination_store, product, on_time, product_qty, driver_identifier, shipment_identifier) VALUES ('{row[1]}', '{row[2]}', '{row[3]}', '{row[4]}', '{row[5]}', '{row[6]}', '{row[7]}')"